apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: vladimish/auth:0.1
        env:
        - name: MARIADB_USER
          value: auth
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-url
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-url
        - name: TOKEN
          value: $(head -c 6 /dev/random | base64)
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP 
      port: 5672
      targetPort: 5672
spec:
  selector:
    app: auth
