apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: vladimish/gateway:0.1
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-url
        - name: TOKEN
          value: $(head -c 6 /dev/random | base64)
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP 
      port: 8081
      targetPort: 8081
      nodePort: 30001
